name:                cone
version:             0.1.0.0
github:              "wehu/cone"
license:             BSD3
author:              "Wei Hu"
maintainer:          "huwei04@hotmail.com"
copyright:           "2021 Wei Hu"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- lib/**/*.cone
- include/**/*.h

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cone#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- array
- lens
- unbound-generics
- fused-effects
- containers
- prettyprinter
- mtl
- directory
- filepath
- split
- optparse-applicative
- process
- pureMD5
- utf8-string

library:
  source-dirs: src

executables:
  cone-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cone

tests:
  cone-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cone
    - hspec
    - text
    - neat-interpolation
